### ISSUE TITLE
Support Relative Paths for System Files

### ISSUE THREAD

**Issue by Sixdd6** [xemu-project/xemu#1945]
### Feature Request

I'd like to package Xemu with my games, strictly for personal use. But the fact that Xemu doesn't allow relative paths means that the package would have to be placed in the exact same location and drive letter every install or I'd have to adjust the paths every time I reinstall the package. I see portable mode is possible but that doesn't solve the issue of the bios and stuff needing absolute paths.

**Comment by Florin9doi** [comment]
You can edit the `xemu.toml` file manually with your relative paths: 
```toml
[sys.files]
bootrom_path  = 'BIOS\bootrom.bin'
flashrom_path = 'BIOS\flashrom.bin'
eeprom_path   = 'eeprom.bin'
hdd_path      = '..\XboxHDDs\hdd.qcow2'
```
